feat: Primeira versão do terratest validando os output do groundwork
mentoriaiac/iac-modulo-rede-oci pull request #11
Opened 2022-02-17 00:16 UTC by StuxxNet

# Primeira versão do terratest validando os output do groundwork

Disponibilizamos a primeira versão do terratest p/ validar os outputs do
módulo de groundwork. Por hora estamos validando o CIDR_Block da VCN, da Subnet
e o nome do compartment.

- [X] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [X] Dê um titulo que expresse o objetivo do PR
- [X] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [X] Descreva o objetivo do PR
- [X] Inclua links relevantes para a sua modificação/sugestão/correção
- [X] Descreva um passo-a-passo para testar o seu PR

## Issue

#10 

## Objetivo

Criar uma primeira versão de terratest para incluir na pipeline.

## Referências

<https://github.com/gruntwork-io/terratest/blob/master/test/terraform_hello_world_example_test.go>

## Como testar

Para executar o terratest siga os passos elencados abaixo:

```bash
cd test
go mod init <nome_do_module> #pode ser qualquer coisa
go get github.com/gruntwork-io/terratest/modules/terraform
go test -v
```

2022-02-17 00:17 UTC, StuxxNet commented
```bash
=== RUN   TestGroundworkModule
TestGroundworkModule 2022-02-16T20:59:35-03:00 retry.go:91: terraform [init -upgrade=false]
TestGroundworkModule 2022-02-16T20:59:35-03:00 logger.go:66: Running command terraform with args [init -upgrade=false]
TestGroundworkModule 2022-02-16T20:59:35-03:00 logger.go:66: Initializing modules...
TestGroundworkModule 2022-02-16T20:59:35-03:00 logger.go:66: 
TestGroundworkModule 2022-02-16T20:59:35-03:00 logger.go:66: Initializing the backend...
TestGroundworkModule 2022-02-16T20:59:35-03:00 logger.go:66: 
TestGroundworkModule 2022-02-16T20:59:35-03:00 logger.go:66: Initializing provider plugins...
TestGroundworkModule 2022-02-16T20:59:35-03:00 logger.go:66: - Reusing previous version of hashicorp/oci from the dependency lock file
TestGroundworkModule 2022-02-16T20:59:36-03:00 logger.go:66: - Using previously-installed hashicorp/oci v4.63.0
TestGroundworkModule 2022-02-16T20:59:36-03:00 logger.go:66: 
TestGroundworkModule 2022-02-16T20:59:36-03:00 logger.go:66: Terraform has been successfully initialized!
TestGroundworkModule 2022-02-16T20:59:36-03:00 logger.go:66: 
TestGroundworkModule 2022-02-16T20:59:36-03:00 logger.go:66: You may now begin working with Terraform. Try running "terraform plan" to see
TestGroundworkModule 2022-02-16T20:59:36-03:00 logger.go:66: any changes that are required for your infrastructure. All Terraform commands
TestGroundworkModule 2022-02-16T20:59:36-03:00 logger.go:66: should now work.
TestGroundworkModule 2022-02-16T20:59:36-03:00 logger.go:66: 
TestGroundworkModule 2022-02-16T20:59:36-03:00 logger.go:66: If you ever set or change modules or backend configuration for Terraform,
TestGroundworkModule 2022-02-16T20:59:36-03:00 logger.go:66: rerun this command to reinitialize your working directory. If you forget, other
TestGroundworkModule 2022-02-16T20:59:36-03:00 logger.go:66: commands will detect it and remind you to do so if necessary.
TestGroundworkModule 2022-02-16T20:59:36-03:00 retry.go:91: terraform [apply -input=false -auto-approve -lock=false]
TestGroundworkModule 2022-02-16T20:59:36-03:00 logger.go:66: Running command terraform with args [apply -input=false -auto-approve -lock=false]
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66: 
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66: Terraform used the selected providers to generate the following execution
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66: plan. Resource actions are indicated with the following symbols:
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:   + create
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66: 
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66: Terraform will perform the following actions:
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66: 
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:   # module.groundwork.oci_core_default_route_table.generated_oci_core_default_route_table will be created
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:   + resource "oci_core_default_route_table" "generated_oci_core_default_route_table" {
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + compartment_id             = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + defined_tags               = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + display_name               = "pub-routetable-01"
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + freeform_tags              = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + id                         = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + manage_default_resource_id = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + state                      = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + time_created               = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66: 
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + route_rules {
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:           + cidr_block        = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:           + description       = "Tráfedo de/para internet"
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:           + destination       = "0.0.0.0/0"
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:           + destination_type  = "CIDR_BLOCK"
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:           + network_entity_id = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:         }
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:     }
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66: 
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:   # module.groundwork.oci_core_internet_gateway.internet_gateway will be created
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:   + resource "oci_core_internet_gateway" "internet_gateway" {
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + compartment_id = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + defined_tags   = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + display_name   = "MentoriaIaC-igw"
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + enabled        = true
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + freeform_tags  = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + id             = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + state          = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + time_created   = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + vcn_id         = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:     }
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66: 
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:   # module.groundwork.oci_core_subnet.subnet will be created
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:   + resource "oci_core_subnet" "subnet" {
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + availability_domain        = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + cidr_block                 = "10.0.0.0/24"
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + compartment_id             = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + defined_tags               = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + dhcp_options_id            = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + display_name               = "MentoriaIaC-subnet"
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + dns_label                  = "MentoriaIaC"
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + freeform_tags              = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + id                         = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + ipv6cidr_block             = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + ipv6virtual_router_ip      = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.go:66:       + prohibit_internet_ingress  = (known after apply)
TestGroundworkModule 2022-02-16T20:59:38-03:00 logger.g [...]

2022-02-20 12:32 UTC, afonsoaugusto requested changes
Opa, show demais seu PR.
Acho que seria legal adicionar um passo-a-passo de como preencher as variáveis para executar os testes e um exemplo do arquivo preenchido e um output quando elas não forem preenchidas.

exemplo de arquivo preenchido:
```terraform.tfvars
tenancy_ocid        = "ocid1.tenancy.oc1..bbbbbbbadsf09834lkgagd980498oifu98403598"
user_ocid           = "ocid1.user.oc1..bbbbbbb987dfasdsaudoiasdufoasi9804983"
private_key_path    = "/home/afonsorodrigues/.oci/oci_api_key.pem"
fingerprint         = "0d:3d:d8:a2:14:e8:9d:89:a3:11:23:10:02:87:90:ed"
region              = "us-ashburn-1"
root_compartment_id = "ocid1.compartment.oc1..bbbbbbbdadf098fsduoiufgd09f8gdflkjdglds0t9r8e34"
```

exemplo output de erro:
```sh
TestGroundworkModule 2022-02-20T08:55:21-03:00 logger.go:66: │ Error: can not create client, bad configuration: did not find a proper configuration for tenancy
TestGroundworkModule 2022-02-20T08:55:21-03:00 logger.go:66: │ 
TestGroundworkModule 2022-02-20T08:55:21-03:00 logger.go:66: │   with provider["registry.terraform.io/hashicorp/oci"],
TestGroundworkModule 2022-02-20T08:55:21-03:00 logger.go:66: │   on terrafile.tf line 1, in provider "oci":
TestGroundworkModule 2022-02-20T08:55:21-03:00 logger.go:66: │    1: provider "oci" {
TestGroundworkModule 2022-02-20T08:55:21-03:00 logger.go:66: │ 
TestGroundworkModule 2022-02-20T08:55:21-03:00 logger.go:66: ╵
TestGroundworkModule 2022-02-20T08:55:21-03:00 retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: can not create client, bad configuration: did not find a proper configuration for tenancy
│ 
│   with provider["registry.terraform.io/hashicorp/oci"],
│   on terrafile.tf line 1, in provider "oci":
│    1: provider "oci" {
│ 
╵}
    apply.go:15: 
        	Error Trace:	apply.go:15
        	            				groundwork_test.go:18
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; ╷
        	            	│ Error: can not create client, bad configuration: did not find a proper configuration for tenancy
        	            	│ 
        	            	│   with provider["registry.terraform.io/hashicorp/oci"],
        	            	│   on terrafile.tf line 1, in provider "oci":
        	            	│    1: provider "oci" {
        	            	│ 
        	            	╵}
        	Test:       	TestGroundworkModule
```

Ou para quando recebermos esse tipo de erro:
```sh
 Error: can not create client, bad configuration: did not find a proper configuration for private key
```

2022-02-20 16:16 UTC, lgfa29 commented on .gitignore
> +*/go.mod
`go.mod` e `go.sum` não deveriam ser ignorados, os dois precisam estar no repositório.

2022-02-20 16:33 UTC, lgfa29 requested changes
Bem legal @StuxxNet! Deixei alguns comentários com melhorias :slightly_smiling_face:

2022-02-20 16:33 UTC, lgfa29 commented on README.md
> +* Antes de executar os testes preencha as variáveis do provider no arquivo "terraform.tfvars" dentro do pasta "how-to-use-this-module" pois ainda não temos uma conta da mentoria. Uma vez com a conta
```suggestion
* Antes de executar os testes preencha as variáveis do provider no arquivo `terraform.tfvars` dentro do pasta `how-to-use-this-module` pois ainda não temos uma conta da mentoria. Uma vez com a conta criada podemos guardar as credenciais nos secrets do GitHub.
```

2022-02-20 16:33 UTC, lgfa29 commented on README.md
> +go get github.com/gruntwork-io/terratest/modules/terraform
Sem ignorar `go.mod` e `go.sum` eu acho que esses passos não são necessários.

2022-02-20 16:33 UTC, lgfa29 commented on outputs.tf
> +  value       = oci_identity_compartment.compartment.name
Eu acho que seria melhor retornar o [`compartment_id`](https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/identity_compartment#compartment_id) já que esse o valor utilizado em outros resources.

Por exemplo:

```hcl
module "groundwork" {
  # ...
}

resource "oci_core_instance" "test_instance" {
  compartment_id = module.groundwork.compartment_id
  # ...
}
```

Com o nome é preciso fazer uma busca do ID antes de poder usar a saída do módulo.

2022-02-20 16:33 UTC, lgfa29 commented on outputs.tf
>  }
Esse símbolo indica que está faltando uma linha em branco no final do arquivo, é bom sempre deixar uma. O `groudwork_test.go` e o `.gitignore` também acabaram ficando sem.

2022-03-02 22:35 UTC, StuxxNet commented on outputs.tf
> +  value       = oci_identity_compartment.compartment.name
Essa output é utilizada para realizar o teste do Terratest. Vou deixar uma output a mais disponível, e essa sim retornará o id do compartment.

2022-12-29 22:31 UTC, closed without merging